# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
multi-ecosystem-groups:
  all:
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all"
    cooldown:
      default-days: 7
  - package-ecosystem: "nix"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    patterns:
      - "*"
    ignore:
      - dependency-name: "anttiharju/*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "cachix/*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    multi-ecosystem-group: "all"
    cooldown:
      default-days: 7
