# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class ${PKG_CLASS} < Formula
  desc '${PKG_DESC}'
  homepage '${PKG_HOMEPAGE}'
  version '${PKG_VERSION}'
  license 'MIT'

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/${PKG_OWNER}/${PKG_REPO}/releases/download/v#{version}/${PKG_REPO}-aarch64-apple-darwin.tar.gz"
      sha256 '${PKG_MAC_ARM_SHA}'

      def install
        bin.install '${PKG_REPO}'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/${PKG_OWNER}/${PKG_REPO}/releases/download/v#{version}/${PKG_REPO}-aarch64-unknown-linux-musl.tar.gz"
      sha256 '${PKG_LINUX_ARM_SHA}'

      def install
        bin.install '${PKG_REPO}'
      end
    end
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/${PKG_OWNER}/${PKG_REPO}/releases/download/v#{version}/${PKG_REPO}-x86_64-unknown-linux-musl.tar.gz"
      sha256 '${PKG_LINUX_INTEL_SHA}'

      def install
        bin.install '${PKG_REPO}'
      end
    end
  end

  test do
    system "#{bin}/${PKG_REPO} --version"
  end
end
