name: "Detect changes"
description: "Decide what steps need running based on changes"
inputs:
  changes:
    description: "JSON array of changed files"
    required: true
runs:
  using: "composite"
  steps:
    - id: actionlint
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard actionlint.yml
    - id: rust
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard rust.yml
    - id: rs
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard rs.yml
    - id: brew
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard brew.yml
    - id: github
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard github.yml
    - id: nix
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard nix.yml
    - id: mkdocs
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard mkdocs.yml
    - id: prettier
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard prettier.yml
    - id: shellcheck
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard shellcheck.yml
    - id: src
      shell: sh
      env:
        array: ${{ inputs.changes }}
      run: |
        compare-changes --changes "$array" --wildcard src.yml
outputs:
  actionlint:
    description: "Whether actionlint has changed"
    value: ${{ steps.actionlint.outputs.changed }}
  rust:
    description: "Whether Rust has changed"
    value: ${{ steps.rust.outputs.changed }}
  rs:
    description: "Whether *.rs has changed"
    value: ${{ steps.rs.outputs.changed }}
  brew:
    description: "Whether Brew has changed"
    value: ${{ steps.brew.outputs.changed }}
  github:
    description: "Whether GitHub has changed"
    value: ${{ steps.github.outputs.changed }}
  nix:
    description: "Whether Nix has changed"
    value: ${{ steps.nix.outputs.changed }}
  release:
    description: "Whether any release has changed"
    value: ${{ steps.brew.outputs.changed || steps.github.outputs.changed || steps.nix.outputs.changed || steps.action.outputs.changed }}
  mkdocs:
    description: "Whether MkDocs has changed"
    value: ${{ steps.mkdocs.outputs.changed }}
  prettier:
    description: "Whether Prettier has changed"
    value: ${{ steps.prettier.outputs.changed }}
  shellcheck:
    description: "Whether ShellCheck has changed"
    value: ${{ steps.shellcheck.outputs.changed }}
  src:
    description: "Whether src has changed"
    value: ${{ steps.src.outputs.changed }}
