name: "Release documentation"
description: "Build and deploy documentation to GitHub Pages"
runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        zensical build --clean
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v5.0.0 # https://github.com/actions/upload-pages-artifact/issues/143
      with:
        path: site
    - name: Deploy pages
      uses: actions/deploy-pages@v5
      id: deployment
