name: "Release GitHub"
description: "Create a GitHub Release"
inputs:
  version:
    description: "Version to release"
    required: true
  anttiharju-bot-id:
    description: "GitHub App ID for anttiharju[bot]"
    required: true
  anttiharju-bot-private-key:
    description: "GitHub App private key for anttiharju[bot]"
    required: true
runs:
  using: "composite"
  steps:
    - name: Tag current commit
      shell: sh
      env:
        tag: "v${{ inputs.version }}"
      run: |
        git tag "$tag"
    - name: Cache
      uses: ./.github/actions/cache
    - name: Create aarch64-apple-darwin archive
      shell: sh
      run: |
        .release/archive.sh aarch64-apple-darwin
    - name: Create aarch64-unknown-linux-musl archive
      shell: sh
      run: |
        .release/archive.sh aarch64-unknown-linux-musl
    - name: Create x86_64-unknown-linux-musl archive
      shell: sh
      run: |
        .release/archive.sh x86_64-unknown-linux-musl
    - name: Release
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
        title: ${{ inputs.version }}
        tag: "v${{ inputs.version }}"
      run: |
        git reset --hard && git clean -df
        git push origin "$tag"
        gh release create "$tag" --title="$title" --generate-notes --draft
        find . -maxdepth 1 -name '${{ github.event.repository.name }}-*.tar.gz' -exec gh release upload "$tag" {} \;
