name: Build
permissions: {}
on:
  push:
    branches:
      - main

jobs:
  plan:
    name: Plan
    uses: ./.github/workflows/plan.yml
    permissions:
      contents: read
      packages: write

  release:
    name: Release
    needs: plan
    runs-on: ubuntu-24.04
    environment: release
    container:
      image: ${{ needs.plan.outputs.container }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    if: needs.plan.outputs.version != ''
    permissions:
      pages: write
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: true

      - name: GitHub
        uses: ./.github/actions/release/github
        with:
          version: ${{ needs.plan.outputs.version }}
          anttiharju-bot-id: ${{ vars.ANTTIHARJU_BOT_ID }}
          anttiharju-bot-private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}

      - name: Nix User Repository
        uses: ./.github/actions/release/nur-packages
        with:
          version: ${{ needs.plan.outputs.version }}
          anttiharju-bot-id: ${{ vars.ANTTIHARJU_BOT_ID }}
          anttiharju-bot-private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}

      - name: Homebrew Tap
        uses: ./.github/actions/release/homebrew-tap
        with:
          version: ${{ needs.plan.outputs.version }}
          anttiharju-bot-id: ${{ vars.ANTTIHARJU_BOT_ID }}
          anttiharju-bot-private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}

      - name: Documentation
        uses: ./.github/actions/release/documentation

      - name: Lock release immutability
        shell: sh
        env:
          GH_TOKEN: ${{ github.token }}
          tag: "v${{ needs.plan.outputs.version }}"
        run: |
          gh release edit "$tag" --draft=false
